#cs

AWSDK For AutoIt v1.0 - AWSDK4AU_Constants.au3

Copyright (c) 2017 Locodarwin

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

#ce

#include-once

; AW Build Number
Const $AW_BUILD = 101

; AW Limits
Const $AW_MAX_AVCHANGE_PER_SECOND  = 10
Const $AW_MAX_MESSAGES_PER_SECOND  = 100
Const $AW_MAX_WHISPERS_PER_SECOND  = 100
Const $AW_MAX_BOTGRAMS_PER_SECOND  = 32
Const $AW_CELL_MIN                 = -32767  ; provided for old applications only
Const $AW_MAX_ATTRIBUTE_LENGTH     = 255
Const $AW_MAX_USER_NAME_LENGTH     = 20
Const $AW_MIN_USER_NAME_LENGTH     = 2
Const $AW_MAX_PASSWORD_LENGTH      = 16
Const $AW_MIN_PASSWORD_LENGTH      = 4
Const $AW_MAX_EMAIL_LENGTH         = 64
Const $AW_MAX_WORLD_NAME_LENGTH    = 16
Const $AW_MAX_LONG_DATA            = 4094

Const $AW_PERSONAL_AVATAR          = 65535
Const $AW_CUSTOM_AVATAR            = 65534
Const $AW_CUSTOM_WORLD_AVATAR      = 65533

; AW Object Versions
Const $AW_OBJECT_VERSION_CAMERA      = 1
Const $AW_OBJECT_VERSION_PARTICLES   = 1
Const $AW_OBJECT_VERSION_ZONE        = 1
Const $AW_OBJECT_VERSION_MOVER       = 1
Const $AW_OBJECT_VERSION_CLOTH       = 1

; AW Attributes
Const $AW_LOGIN_NAME = 0
Const $AW_LOGIN_PASSWORD = 1
Const $AW_LOGIN_OWNER = 2
Const $AW_LOGIN_PRIVILEGE_PASSWORD = 3
Const $AW_LOGIN_PRIVILEGE_NUMBER = 4
Const $AW_LOGIN_PRIVILEGE_NAME = 5
Const $AW_LOGIN_APPLICATION = 6
Const $AW_LOGIN_EMAIL = 7
Const $AW_UNIVERSE_BROWSER_MINIMUM = 8
Const $AW_UNIVERSE_BROWSER_RELEASE = 9
Const $AW_UNIVERSE_BROWSER_BETA = 10
Const $AW_UNIVERSE_WORLD_MINIMUM = 11
Const $AW_UNIVERSE_WORLD_START = 12
Const $AW_UNIVERSE_REGISTRATION_REQUIRED = 13
Const $AW_UNIVERSE_BUILD_NUMBER = 14
Const $AW_UNIVERSE_MONTHLY_CHARGE =15
Const $AW_UNIVERSE_ANNUAL_CHARGE = 16
Const $AW_UNIVERSE_REGISTER_METHOD = 17
Const $AW_UNIVERSE_TIME = 18
Const $AW_UNIVERSE_CITIZEN_CHANGES_ALLOWED = 19
Const $AW_UNIVERSE_BROWSER_RELEASE_22 = 20
Const $AW_UNIVERSE_WELCOME_MESSAGE = 21
Const $AW_UNIVERSE_WORLD_RELEASE = 22
Const $AW_UNIVERSE_WORLD_BETA = 23
Const $AW_UNIVERSE_ALLOW_TOURISTS = 24
Const $AW_UNIVERSE_SEARCH_URL = 25
Const $AW_UNIVERSE_NOTEPAD_URL = 26
Const $AW_UNIVERSE_NAME = 27
Const $AW_UNIVERSE_USER_LIST_ENABLED = 28
Const $AW_CITIZEN_NUMBER = 29
Const $AW_CITIZEN_NAME = 30
Const $AW_CITIZEN_PASSWORD = 31
Const $AW_CITIZEN_EMAIL = 32
Const $AW_CITIZEN_TIME_LEFT = 33
Const $AW_CITIZEN_PRIVILEGE_PASSWORD = 34
Const $AW_CITIZEN_IMMIGRATION_TIME = 35
Const $AW_CITIZEN_EXPIRATION_TIME = 36
Const $AW_CITIZEN_BETA = 37
Const $AW_CITIZEN_LAST_LOGIN = 38
Const $AW_CITIZEN_BOT_LIMIT = 39
Const $AW_CITIZEN_TOTAL_TIME = 40
Const $AW_CITIZEN_ENABLED = 41
Const $AW_CITIZEN_COMMENT = 42
Const $AW_CITIZEN_URL = 43
Const $AW_WORLD_NAME = 44
Const $AW_WORLD_TITLE = 45
Const $AW_WORLD_BACKDROP = 46
Const $AW_WORLD_GROUND = 47
Const $AW_WORLD_OBJECT_PATH = 48
Const $AW_WORLD_OBJECT_REFRESH = 49
Const $AW_WORLD_BUILD_RIGHT = 50
Const $AW_WORLD_EMINENT_DOMAIN_RIGHT = 51
Const $AW_WORLD_ENTER_RIGHT = 52
Const $AW_WORLD_SPECIAL_OBJECTS_RIGHT = 53
Const $AW_WORLD_FOG_RED = 54
Const $AW_WORLD_FOG_GREEN = 55
Const $AW_WORLD_FOG_BLUE = 56
Const $AW_WORLD_CARETAKER_CAPABILITY = 57
Const $AW_WORLD_RESTRICTED_RADIUS = 58
Const $AW_WORLD_PUBLIC_SPEAKER_CAPABILITY = 59
Const $AW_WORLD_PUBLIC_SPEAKER_RIGHT = 60
Const $AW_WORLD_CREATION_TIMESTAMP = 61
Const $AW_WORLD_HOME_PAGE = 62
Const $AW_WORLD_BUILD_NUMBER = 63
Const $AW_WORLD_OBJECT_PASSWORD = 64
Const $AW_WORLD_DISABLE_CREATE_URL = 65
Const $AW_WORLD_RATING = 66
Const $AW_WORLD_WELCOME_MESSAGE = 67
Const $AW_WORLD_EJECT_RIGHT = 68
Const $AW_WORLD_EJECT_CAPABILITY = 69
Const $AW_WORLD_CELL_LIMIT = 70
Const $AW_WORLD_BUILD_CAPABILITY = 71
Const $AW_WORLD_ALLOW_PASSTHRU = 72
Const $AW_WORLD_ALLOW_FLYING = 73
Const $AW_WORLD_ALLOW_TELEPORT = 74
Const $AW_WORLD_ALLOW_OBJECT_SELECT = 75
Const $AW_WORLD_BOTS_RIGHT = 76
Const $AW_WORLD_SPEAK_CAPABILITY = 77
Const $AW_WORLD_SPEAK_RIGHT = 78
Const $AW_WORLD_ALLOW_TOURIST_WHISPER = 79
Const $AW_WORLD_LIGHT_X = 80
Const $AW_WORLD_LIGHT_Y = 81
Const $AW_WORLD_LIGHT_Z = 82
Const $AW_WORLD_LIGHT_RED = 83
Const $AW_WORLD_LIGHT_GREEN = 84
Const $AW_WORLD_LIGHT_BLUE = 85
Const $AW_WORLD_AMBIENT_LIGHT_RED = 86
Const $AW_WORLD_AMBIENT_LIGHT_GREEN = 87
Const $AW_WORLD_AMBIENT_LIGHT_BLUE = 88
Const $AW_WORLD_ALLOW_AVATAR_COLLISION = 89
Const $AW_WORLD_FOG_ENABLE = 90
Const $AW_WORLD_FOG_MINIMUM = 91
Const $AW_WORLD_FOG_MAXIMUM = 92
Const $AW_WORLD_FOG_TINTED = 93
Const $AW_WORLD_MAX_USERS = 94
Const $AW_WORLD_SIZE = 95
Const $AW_WORLD_OBJECT_COUNT = 96
Const $AW_WORLD_EXPIRATION = 97
Const $AW_WORLD_SPECIAL_COMMANDS_RIGHT = 98
Const $AW_WORLD_MAX_LIGHT_RADIUS = 99
Const $AW_WORLD_SKYBOX = 100
Const $AW_WORLD_MINIMUM_VISIBILITY = 101
Const $AW_WORLD_REPEATING_GROUND = 102
Const $AW_WORLD_KEYWORDS = 103
Const $AW_WORLD_ENABLE_TERRAIN = 104
Const $AW_WORLD_ALLOW_3_AXIS_ROTATION = 105
Const $AW_WORLD_TERRAIN_TIMESTAMP = 106
Const $AW_WORLD_ENTRY_POINT = 107
Const $AW_WORLD_SKY_NORTH_RED = 108
Const $AW_WORLD_SKY_NORTH_GREEN = 109
Const $AW_WORLD_SKY_NORTH_BLUE = 110
Const $AW_WORLD_SKY_SOUTH_RED = 111
Const $AW_WORLD_SKY_SOUTH_GREEN = 112
Const $AW_WORLD_SKY_SOUTH_BLUE = 113
Const $AW_WORLD_SKY_EAST_RED = 114
Const $AW_WORLD_SKY_EAST_GREEN = 115
Const $AW_WORLD_SKY_EAST_BLUE = 116
Const $AW_WORLD_SKY_WEST_RED = 117
Const $AW_WORLD_SKY_WEST_GREEN = 118
Const $AW_WORLD_SKY_WEST_BLUE = 119
Const $AW_WORLD_SKY_TOP_RED = 120
Const $AW_WORLD_SKY_TOP_GREEN = 121
Const $AW_WORLD_SKY_TOP_BLUE = 122
Const $AW_WORLD_SKY_BOTTOM_RED = 123
Const $AW_WORLD_SKY_BOTTOM_GREEN = 124
Const $AW_WORLD_SKY_BOTTOM_BLUE = 125
Const $AW_WORLD_CLOUDS_LAYER1_TEXTURE = 126
Const $AW_WORLD_CLOUDS_LAYER1_MASK = 127
Const $AW_WORLD_CLOUDS_LAYER1_TILE = 128
Const $AW_WORLD_CLOUDS_LAYER1_SPEED_X = 129
Const $AW_WORLD_CLOUDS_LAYER1_SPEED_Z = 130
Const $AW_WORLD_CLOUDS_LAYER1_OPACITY = 131
Const $AW_WORLD_CLOUDS_LAYER2_TEXTURE = 132
Const $AW_WORLD_CLOUDS_LAYER2_MASK = 133
Const $AW_WORLD_CLOUDS_LAYER2_TILE = 134
Const $AW_WORLD_CLOUDS_LAYER2_SPEED_X = 135
Const $AW_WORLD_CLOUDS_LAYER2_SPEED_Z = 136
Const $AW_WORLD_CLOUDS_LAYER2_OPACITY = 137
Const $AW_WORLD_CLOUDS_LAYER3_TEXTURE = 138
Const $AW_WORLD_CLOUDS_LAYER3_MASK = 139
Const $AW_WORLD_CLOUDS_LAYER3_TILE = 140
Const $AW_WORLD_CLOUDS_LAYER3_SPEED_X = 141
Const $AW_WORLD_CLOUDS_LAYER3_SPEED_Z = 142
Const $AW_WORLD_CLOUDS_LAYER3_OPACITY = 143
Const $AW_WORLD_DISABLE_CHAT = 144
Const $AW_WORLD_ALLOW_CITIZEN_WHISPER = 145
Const $AW_WORLD_ALWAYS_SHOW_NAMES = 146
Const $AW_WORLD_DISABLE_AVATAR_LIST = 147
Const $AW_WORLD_AVATAR_REFRESH_RATE = 148
Const $AW_WORLD_WATER_TEXTURE = 149
Const $AW_WORLD_WATER_MASK = 150
Const $AW_WORLD_WATER_BOTTOM_TEXTURE = 151
Const $AW_WORLD_WATER_BOTTOM_MASK = 152
Const $AW_WORLD_WATER_OPACITY = 153
Const $AW_WORLD_WATER_RED = 154
Const $AW_WORLD_WATER_GREEN = 155
Const $AW_WORLD_WATER_BLUE = 156
Const $AW_WORLD_WATER_LEVEL = 157
Const $AW_WORLD_WATER_SURFACE_MOVE = 158
Const $AW_WORLD_WATER_WAVE_MOVE = 159
Const $AW_WORLD_WATER_SPEED = 160
Const $AW_WORLD_WATER_ENABLED = 161
Const $AW_WORLD_EMINENT_DOMAIN_CAPABILITY = 162
Const $AW_WORLD_LIGHT_TEXTURE = 163
Const $AW_WORLD_LIGHT_MASK = 164
Const $AW_WORLD_LIGHT_DRAW_SIZE = 165
Const $AW_WORLD_LIGHT_DRAW_FRONT = 166
Const $AW_WORLD_LIGHT_DRAW_BRIGHT = 167
Const $AW_WORLD_LIGHT_SOURCE_USE_COLOR = 168
Const $AW_WORLD_LIGHT_SOURCE_COLOR = 169
Const $AW_WORLD_TERRAIN_AMBIENT = 170
Const $AW_WORLD_TERRAIN_DIFFUSE = 171
Const $AW_WORLD_WATER_VISIBILITY = 172
Const $AW_WORLD_SOUND_FOOTSTEP = 173
Const $AW_WORLD_SOUND_WATER_ENTER = 174
Const $AW_WORLD_SOUND_WATER_EXIT = 175
Const $AW_WORLD_SOUND_AMBIENT = 176
Const $AW_WORLD_GRAVITY = 177
Const $AW_WORLD_BUOYANCY = 178
Const $AW_WORLD_FRICTION = 179
Const $AW_WORLD_WATER_FRICTION = 180
Const $AW_WORLD_SLOPESLIDE_ENABLED = 181
Const $AW_WORLD_SLOPESLIDE_MIN_ANGLE = 182
Const $AW_WORLD_SLOPESLIDE_MAX_ANGLE = 183
Const $AW_WORLD_ALLOW_TOURIST_BUILD = 184
Const $AW_WORLD_ENABLE_REFERER = 185
Const $AW_WORLD_WATER_UNDER_TERRAIN = 186
Const $AW_WORLD_TERRAIN_OFFSET = 187
Const $AW_WORLD_VOIP_RIGHT = 188
Const $AW_WORLD_DISABLE_MULTIPLE_MEDIA = 189
Const $AW_WORLD_BOTMENU_URL = 190
Const $AW_WORLD_ENABLE_BUMP_EVENT = 191
Const $AW_WORLD_ENABLE_SYNC_EVENTS = 192
Const $AW_WORLD_ENABLE_CAV = 193
Const $AW_WORLD_ENABLE_PAV = 194
Const $AW_WORLD_CHAT_DISABLE_URL_CLICKS = 195
Const $AW_WORLD_MOVER_EMPTY_RESET_TIMEOUT = 196
Const $AW_WORLD_MOVER_USED_RESET_TIMEOUT = 197

; AW My Constants
Const $AW_MY_X = 198
Const $AW_MY_Y = 199
Const $AW_MY_Z = 200
Const $AW_MY_YAW = 201
Const $AW_MY_PITCH = 202
Const $AW_MY_TYPE = 203
Const $AW_MY_GESTURE = 204
Const $AW_MY_STATE = 205

; AW Avatar Constants
Const $AW_AVATAR_SESSION = 206
Const $AW_AVATAR_NAME = 207
Const $AW_AVATAR_X = 208
Const $AW_AVATAR_Y = 209
Const $AW_AVATAR_Z = 210
Const $AW_AVATAR_YAW = 211
Const $AW_AVATAR_PITCH = 212
Const $AW_AVATAR_TYPE = 213
Const $AW_AVATAR_GESTURE = 214
Const $AW_AVATAR_STATE = 215
Const $AW_AVATAR_ADDRESS = 216
Const $AW_AVATAR_VERSION = 217
Const $AW_AVATAR_CITIZEN = 218
Const $AW_AVATAR_PRIVILEGE = 219
Const $AW_AVATAR_LOCK = 220
Const $AW_AVATAR_FLAGS = 221
Const $AW_CHAT_SESSION = 222
Const $AW_CHAT_MESSAGE = 223
Const $AW_CELL_X = 224
Const $AW_CELL_Z = 225
Const $AW_CELL_SEQUENCE = 226
Const $AW_CELL_SIZE = 227
Const $AW_CELL_ITERATOR = 228
Const $AW_CELL_COMBINE = 229
Const $AW_OBJECT_ID = 230
Const $AW_OBJECT_NUMBER = 231
Const $AW_OBJECT_X = 232
Const $AW_OBJECT_Y = 233
Const $AW_OBJECT_Z = 234
Const $AW_OBJECT_YAW = 235
Const $AW_OBJECT_TILT = 236
Const $AW_OBJECT_ROLL = 237
Const $AW_OBJECT_MODEL = 238
Const $AW_OBJECT_DESCRIPTION = 239
Const $AW_OBJECT_ACTION = 240
Const $AW_OBJECT_OLD_NUMBER = 241
Const $AW_OBJECT_OLD_X = 242
Const $AW_OBJECT_OLD_Z = 243
Const $AW_OBJECT_OWNER = 244
Const $AW_OBJECT_SESSION = 245
Const $AW_OBJECT_BUILD_TIMESTAMP = 246
Const $AW_OBJECT_SYNC = 247
Const $AW_OBJECT_TYPE = 248
Const $AW_OBJECT_DATA = 249

Const $AW_QUERY_COMPLETE 			= 250
Const $AW_CHAT_TYPE 				= 251
Const $AW_LICENSE_NAME 				= 252
Const $AW_LICENSE_PASSWORD 			= 253
Const $AW_LICENSE_USERS 			= 254
Const $AW_LICENSE_RANGE 			= 255
Const $AW_LICENSE_EMAIL 			= 256
Const $AW_LICENSE_COMMENT 			= 257
Const $AW_LICENSE_CREATION_TIME 	= 258
Const $AW_LICENSE_EXPIRATION_TIME	= 259
Const $AW_LICENSE_LAST_START		= 260
Const $AW_LICENSE_LAST_ADDRESS 		= 261
Const $AW_LICENSE_HIDDEN 			= 262
Const $AW_LICENSE_ALLOW_TOURISTS 	= 263
Const $AW_LICENSE_VOIP 				= 264
Const $AW_LICENSE_PLUGINS 			= 265
Const $AW_WORLDLIST_NAME 			= 266
Const $AW_WORLDLIST_STATUS 			= 267
Const $AW_WORLDLIST_USERS 			= 268
Const $AW_WORLDLIST_RATING 			= 269
Const $AW_WORLDLIST_MORE 			= 270
Const $AW_EJECT_SESSION 			= 271
Const $AW_EJECT_DURATION 			= 272
Const $AW_EJECTION_TYPE 			= 273
Const $AW_EJECTION_ADDRESS 			= 274
Const $AW_EJECTION_EXPIRATION_TIME 	= 275
Const $AW_EJECTION_CREATION_TIME 	= 276
Const $AW_EJECTION_COMMENT 			= 277
Const $AW_DISCONNECT_REASON			= 278
Const $AW_FILE_RECIPIENT 			= 279
Const $AW_FILE_SENDER 				= 280
Const $AW_FILE_SENDER_NAME 			= 281
Const $AW_FILE_SESSION 				= 282
Const $AW_FILE_ADDRESS 				= 283
Const $AW_FILE_PORT 				= 284
Const $AW_CLICKED_SESSION 			= 285
Const $AW_CLICKED_NAME 				= 286
Const $AW_URL_NAME 					= 287
Const $AW_URL_POST 					= 288
Const $AW_URL_TARGET 				= 289
Const $AW_URL_TARGET_3D 			= 290
Const $AW_TELEPORT_WORLD 			= 291
Const $AW_TELEPORT_X 				= 292
Const $AW_TELEPORT_Y 				= 293
Const $AW_TELEPORT_Z 				= 294
Const $AW_TELEPORT_YAW 				= 295
Const $AW_TELEPORT_WARP 			= 296
Const $AW_SERVER_BUILD 				= 297
Const $AW_SERVER_NAME 				= 298
Const $AW_SERVER_PASSWORD 			= 299
Const $AW_SERVER_REGISTRY 			= 300
Const $AW_SERVER_CARETAKERS 		= 301
Const $AW_SERVER_ID 				= 302
Const $AW_SERVER_INSTANCE 			= 303
Const $AW_SERVER_ENABLED 			= 304
Const $AW_SERVER_STATE 				= 305
Const $AW_SERVER_USERS 				= 306
Const $AW_SERVER_MAX_USERS 			= 307
Const $AW_SERVER_OBJECTS 			= 308
Const $AW_SERVER_SIZE 				= 309
Const $AW_SERVER_EXPIRATION 		= 310
Const $AW_SERVER_START_RC 			= 311
Const $AW_SERVER_MORE 				= 312
Const $AW_SERVER_TERRAIN_NODES 		= 313
Const $AW_TERRAIN_X 				= 314
Const $AW_TERRAIN_Z 				= 315
Const $AW_TERRAIN_PAGE_X 			= 316
Const $AW_TERRAIN_PAGE_Z 			= 317
Const $AW_TERRAIN_NODE_X 			= 318
Const $AW_TERRAIN_NODE_Z 			= 319
Const $AW_TERRAIN_NODE_SIZE 		= 320
Const $AW_TERRAIN_NODE_TEXTURE_COUNT = 321
Const $AW_TERRAIN_NODE_HEIGHT_COUNT = 322
Const $AW_TERRAIN_NODE_TEXTURES 	= 323
Const $AW_TERRAIN_NODE_HEIGHTS 		= 324
Const $AW_TERRAIN_SEQUENCE 			= 325
Const $AW_TERRAIN_COMPLETE 			= 326
Const $AW_TERRAIN_VERSION_NEEDED 	= 327
Const $AW_ENTER_GLOBAL 				= 328
Const $AW_CONSOLE_RED 				= 329
Const $AW_CONSOLE_GREEN 			= 330
Const $AW_CONSOLE_BLUE 				= 331
Const $AW_CONSOLE_BOLD 				= 332
Const $AW_CONSOLE_ITALICS 			= 333
Const $AW_CONSOLE_MESSAGE 			= 334
Const $AW_BOTGRAM_TO 				= 335
Const $AW_BOTGRAM_FROM 				= 336
Const $AW_BOTGRAM_FROM_NAME 		= 337
Const $AW_BOTGRAM_TYPE 				= 338
Const $AW_BOTGRAM_TEXT				= 339
Const $AW_TOOLBAR_ID 				= 340
Const $AW_TOOLBAR_SESSION 			= 341
Const $AW_USERLIST_MORE 			= 342
Const $AW_USERLIST_NAME 			= 343
Const $AW_USERLIST_WORLD 			= 344
Const $AW_USERLIST_EMAIL 			= 345
Const $AW_USERLIST_CITIZEN 			= 346
Const $AW_USERLIST_PRIVILEGE 		= 347
Const $AW_USERLIST_STATE 			= 348
Const $AW_USERLIST_ADDRESS 			= 349
Const $AW_USERLIST_ID 				= 350
Const $AW_SOUND_NAME 				= 351
Const $AW_CAMERA_LOCATION_TYPE 		= 352
Const $AW_CAMERA_LOCATION_OBJECT 	= 353
Const $AW_CAMERA_LOCATION_SESSION 	= 354
Const $AW_CAMERA_TARGET_TYPE 		= 355
Const $AW_CAMERA_TARGET_OBJECT 		= 356
Const $AW_CAMERA_TARGET_SESSION 	= 357
Const $AW_PLUGIN_STRING 			= 358
Const $AW_BOTMENU_TO_SESSION 		= 359
Const $AW_BOTMENU_FROM_NAME 		= 360
Const $AW_BOTMENU_FROM_SESSION 		= 361
Const $AW_BOTMENU_QUESTION 			= 362
Const $AW_BOTMENU_ANSWER 			= 363

 ; attributes below are not used by the SDK
#cs
  AW_CONTACT_NUMBER
  AW_CONTACT_STATUS
  AW_CONTACT_NAME
  AW_CONTACT_WORLD
  AW_CONTACT_MORE
  AW_CONTACT_OPTIONS
  AW_TELEGRAM_TO
  AW_TELEGRAM_FROM
  AW_TELEGRAM_TEXT
  AW_TELEGRAM_SENT
  AW_TELEGRAM_MORE
  AW_JOIN_NAME
  AW_JOIN_CITIZEN
  AW_JOIN_WORLD
  AW_JOIN_X
  AW_JOIN_Y
  AW_JOIN_Z
  AW_JOIN_YAW
  AW_REGISTER_CC_NAME
  AW_REGISTER_CC_NUMBER
  AW_REGISTER_CC_MONTH
  AW_REGISTER_CC_YEAR
  AW_REGISTER_ADDRESS
  AW_REGISTER_CITY
  AW_REGISTER_STATE
  AW_REGISTER_ZIP
  AW_REGISTER_PHONE_NUMBER
  AW_REGISTER_BUSINESS_NAME
  AW_REGISTER_VENDOR
  AW_REGISTER_RESULT
  AW_REGISTER_METHOD
  AW_VOIP_DATA
#ce

  ; attributes below are used by the SDK
Const $AW_UNIVERSE_CAV_PATH 		= 396
Const $AW_CITIZEN_PAV_ENABLED		= 397
Const $AW_CAV_CITIZEN				= 398
Const $AW_CAV_DEFINITION			= 399
Const $AW_ENTITY_TYPE				= 400
Const $AW_ENTITY_ID					= 401
Const $AW_ENTITY_STATE				= 402
Const $AW_ENTITY_FLAGS				= 403
Const $AW_ENTITY_X					= 404
Const $AW_ENTITY_Y					= 405
Const $AW_ENTITY_Z					= 406
Const $AW_ENTITY_YAW				= 407
Const $AW_ENTITY_PITCH				= 408
Const $AW_ENTITY_ROLL				= 409
Const $AW_ENTITY_OWNER_SESSION		= 410
Const $AW_ENTITY_OWNER_CITIZEN		= 411
Const $AW_AVATAR_DISTANCE			= 412
Const $AW_AVATAR_ANGLE				= 413
Const $AW_AVATAR_Y_DELTA			= 414
Const $AW_AVATAR_YAW_DELTA			= 415
Const $AW_AVATAR_PITCH_DELTA		= 416
Const $AW_AVATAR_WORLD_INSTANCE		= 417
Const $AW_ATTRIB_SENDER_SESSION		= 418
Const $AW_ENTITY_MODEL_NUM			= 419
Const $AW_WORLD_V4_OBJECTS_RIGHT	= 420
Const $AW_CITIZEN_LAST_ADDRESS		= 421
Const $AW_HUD_ELEMENT_TYPE			= 422
Const $AW_HUD_ELEMENT_ID			= 423
Const $AW_HUD_ELEMENT_SESSION		= 424
Const $AW_HUD_ELEMENT_ORIGIN		= 425
Const $AW_HUD_ELEMENT_X				= 426
Const $AW_HUD_ELEMENT_Y				= 427
Const $AW_HUD_ELEMENT_Z				= 428
Const $AW_HUD_ELEMENT_FLAGS			= 429
Const $AW_HUD_ELEMENT_TEXT			= 430
Const $AW_HUD_ELEMENT_COLOR			= 431
Const $AW_HUD_ELEMENT_OPACITY		= 432
Const $AW_HUD_ELEMENT_SIZE_X		= 433
Const $AW_HUD_ELEMENT_SIZE_Y		= 434
Const $AW_HUD_ELEMENT_SIZE_Z		= 435
Const $AW_HUD_ELEMENT_CLICK_X		= 436
Const $AW_HUD_ELEMENT_CLICK_Y		= 437
Const $AW_HUD_ELEMENT_CLICK_Z		= 438
Const $AW_HUD_ELEMENT_TEXTURE_OFFSET_X	= 439
Const $AW_HUD_ELEMENT_TEXTURE_OFFSET_Y	= 440

Const $AW_CITIZEN_PRIVACY				= 441
Const $AW_CITIZEN_TRIAL					= 442
Const $AW_UNIVERSE_CAV_PATH2			= 443
Const $AW_WORLD_DISABLE_SHADOWS			= 444
Const $AW_WORLD_ENABLE_CAMERA_COLLISION	= 445
Const $AW_WORLD_SPECIAL_COMMANDS		= 446
Const $AW_UNIVERSE_OBJECT_REFRESH		= 447
Const $AW_UNIVERSE_OBJECT_PASSWORD		= 448
Const $AW_CAV_SESSION					= 449
Const $AW_CITIZEN_CAV_ENABLED			= 450
Const $AW_WORLD_CAV_OBJECT_PATH			= 451
Const $AW_WORLD_CAV_OBJECT_PASSWORD		= 452
Const $AW_WORLD_CAV_OBJECT_REFRESH		= 453
Const $AW_OBJECT_CALLBACK_REFERENCE		= 454
Const $AW_WORLD_TERRAIN_RIGHT			= 455
Const $AW_UNIVERSE_ALLOW_TOURISTS_CAV	= 456
Const $AW_UNIVERSE_ALLOW_BOTS_CAV		= 457
Const $AW_WORLD_VOIP_CONFERENCE_GLOBAL	= 458
Const $AW_WORLD_VOIP_MODERATE_GLOBAL	= 459
Const $AW_OBJECT_SESSION_TO				= 460
Const $AW_WORLD_CAMERA_ZOOM				= 461
Const $AW_WORLD_WAIT_LIMIT				= 462

Const $AW_XFER_DISCONNECT_REASON		= 463
Const $AW_XFER_TYPE						= 464
Const $AW_XFER_FROM_SESSION				= 465
Const $AW_XFER_FROM_NAME				= 466
Const $AW_XFER_TO_SESSION				= 467
Const $AW_XFER_TO_NAME					= 468
Const $AW_XFER_TO_WORLD_NAME			= 469
Const $AW_XFER_TO_ZONE_NAME				= 470
Const $AW_XFER_TO_TAG_NAME				= 471
Const $AW_XFER_DATA_ID					= 472
Const $AW_XFER_DATA_FILE_NAME			= 473
Const $AW_XFER_DATA_LEN_TOTAL			= 474
Const $AW_XFER_DATA_LEN_OFFSET			= 475
Const $AW_XFER_DATA						= 476
Const $AW_XFER_DATA2					= 477
Const $AW_XFER_DATA3					= 478
Const $AW_XFER_DATA_MORE				= 479
Const $AW_XFER_RC						= 480
Const $AW_XFER_SHOW_NAME				= 481
Const $AW_XFER_OPTIONS					= 482
Const $AW_XFER_EXPIRATION				= 483
Const $AW_LICENSE_XFER_SHOW_RIGHTS		= 484
Const $AW_XFER_SHOW_CAPABILITY			= 485
Const $AW_XFER_SHOW_SEQUENCE			= 486

Const $AW_LASER_BEAM_SOURCE_TYPE		= 487
Const $AW_LASER_BEAM_SOURCE_ID			= 488
Const $AW_LASER_BEAM_SOURCE_X			= 490
Const $AW_LASER_BEAM_SOURCE_Y			= 491
Const $AW_LASER_BEAM_SOURCE_Z			= 492
Const $AW_LASER_BEAM_TARGET_TYPE		= 493
Const $AW_LASER_BEAM_TARGET_ID			= 494
Const $AW_LASER_BEAM_TARGET_X			= 495
Const $AW_LASER_BEAM_TARGET_Y			= 496
Const $AW_LASER_BEAM_TARGET_Z			= 497
Const $AW_LASER_BEAM_STYLE				= 498
Const $AW_LASER_BEAM_COLOR				= 499
Const $AW_LASER_BEAM_DEFINITION			= 500

Const $AW_WORLD_VOIPCAST_HOST			= 501
Const $AW_WORLD_VOIPCAST_PORT			= 502

Const $AW_MY_ZONE						= 503
Const $AW_AVATAR_ZONE					= 504

Const $AW_UNIVERSE_PER_CITIZEN_CAV		= 505

Const $AW_XFER_OWNER					= 506

Const $AW_WORLD_ENABLE_WIREFRAME		= 507

Const $AW_SHOPITEM_ID					= 508
Const $AW_SHOPITEM_CREATION				= 509
Const $AW_SHOPITEM_EXPIRATION			= 510
Const $AW_SHOPITEM_PRICE				= 511
Const $AW_SHOPITEM_TYPE					= 512
Const $AW_SHOPITEM_CATEGORY				= 513
Const $AW_SHOPITEM_DESCRIPTION			= 514
Const $AW_SHOPITEM_OBJECT				= 515
Const $AW_SHOPITEM_DEFINITION			= 516

Const $AW_SHOPTRANS_ID					= 517
Const $AW_SHOPTRANS_CITIZEN				= 518
Const $AW_SHOPTRANS_ITEMID				= 519
Const $AW_SHOPTRANS_AMOUNT				= 520
Const $AW_SHOPTRANS_DATE				= 521
Const $AW_SHOPTRANS_SELLER				= 522
Const $AW_SHOPTRANS_COMMENT				= 523
Const $AW_SHOPTRANS_TOTAL				= 524
Const $AW_SHOPTRANS_ITERATOR			= 525
Const $AW_SHOPTRANS_MORE				= 526

Const $AW_SHOPITEM_CHANGED				= 527
Const $AW_LICENSE_SHOP					= 528

Const $AW_CITIZEN_PWD_EXP				= 529
Const $AW_UNIVERSE_EXPIRATION_DATE		= 530
Const $AW_UNIVERSE_IMMIGRATION			= 531
Const $AW_CITIZEN_SEC_PASSWORD			= 532

Const $AW_CHAT_CHANNEL					= 533
Const $AW_CHAT_CITIZEN					= 534
Const $AW_WORLD_CHAT_CHANNEL1_NAME		= 535
Const $AW_WORLD_CHAT_CHANNEL2_NAME		= 536
Const $AW_WORLD_CHAT_CHANNEL3_NAME		= 537
Const $AW_WORLD_CHAT_CHANNEL4_NAME		= 538
Const $AW_WORLD_CHAT_CHANNEL5_NAME		= 539
Const $AW_WORLD_CHAT_CHANNEL1_COLOR		= 540
Const $AW_WORLD_CHAT_CHANNEL2_COLOR		= 541
Const $AW_WORLD_CHAT_CHANNEL3_COLOR		= 542
Const $AW_WORLD_CHAT_CHANNEL4_COLOR		= 543
Const $AW_WORLD_CHAT_CHANNEL5_COLOR		= 544
Const $AW_WORLDLIST_BOTS				= 545
Const $AW_MAX_ATTRIBUTE					= 546


;AW Event Constants
Const $AW_EVENT_AVATAR_ADD = 0
Const $AW_EVENT_AVATAR_CHANGE = 1
Const $AW_EVENT_AVATAR_DELETE = 2
Const $AW_EVENT_CELL_BEGIN = 3
Const $AW_EVENT_CELL_OBJECT = 4
Const $AW_EVENT_CELL_END = 5
Const $AW_EVENT_CHAT = 6
Const $AW_EVENT_OBJECT_ADD = 7
Const $AW_EVENT_OBJECT_DELETE = 8
Const $AW_EVENT_UNIVERSE_ATTRIBUTES = 9
Const $AW_EVENT_UNIVERSE_DISCONNECT = 10
Const $AW_EVENT_WORLD_ATTRIBUTES = 11
Const $AW_EVENT_WORLD_INFO = 12
Const $AW_EVENT_WORLD_DISCONNECT = 13
Const $AW_EVENT_SEND_FILE = 14
Const $AW_EVENT_CONTACT_STATE = 15
Const $AW_EVENT_TELEGRAM = 16
Const $AW_EVENT_JOIN = 17
Const $AW_EVENT_OBJECT_CLICK = 18
Const $AW_EVENT_OBJECT_SELECT = 19
Const $AW_EVENT_AVATAR_CLICK = 20
Const $AW_EVENT_URL = 21
Const $AW_EVENT_URL_CLICK = 22
Const $AW_EVENT_TELEPORT = 23
Const $AW_EVENT_ADMIN_WORLD_INFO = 24
Const $AW_EVENT_ADMIN_WORLD_DELETE = 25
Const $AW_EVENT_TERRAIN_BEGIN = 26
Const $AW_EVENT_TERRAIN_DATA = 27
Const $AW_EVENT_TERRAIN_END = 28
Const $AW_EVENT_CONSOLE_MESSAGE = 29
Const $AW_EVENT_TERRAIN_CHANGED = 30
Const $AW_EVENT_BOTGRAM = 31
Const $AW_EVENT_TOOLBAR_CLICK = 32
Const $AW_EVENT_USER_INFO = 33
Const $AW_EVENT_VOIP_DATA = 34
Const $AW_EVENT_NOISE = 35
Const $AW_EVENT_CAMERA = 36
Const $AW_EVENT_BOTMENU = 37
Const $AW_EVENT_OBJECT_BUMP = 38
Const $AW_EVENT_ENTITY_ADD = 39
Const $AW_EVENT_ENTITY_CHANGE = 40
Const $AW_EVENT_ENTITY_DELETE = 41
Const $AW_EVENT_ENTITY_RIDER_ADD = 42
Const $AW_EVENT_ENTITY_RIDER_DELETE = 43
Const $AW_EVENT_ENTITY_RIDER_CHANGE = 44
Const $AW_EVENT_AVATAR_RELOAD = 45
Const $AW_EVENT_ENTITY_LINKS = 46
Const $AW_EVENT_HUD_CLICK = 47
Const $AW_EVENT_HUD_CREATE = 48
Const $AW_EVENT_HUD_DESTROY = 49
Const $AW_EVENT_HUD_CLEAR = 50
Const $AW_EVENT_CAV_DEFINITION_CHANGE = 51
Const $AW_EVENT_WORLD_CAV_DEFINITION_CHANGE = 52

Const $AW_EVENT_XFER_DISCONNECT			= 53
Const $AW_EVENT_XFER_OFFER				= 54
Const $AW_EVENT_XFER_REPLY				= 55
Const $AW_EVENT_XFER_SEND				= 56
Const $AW_EVENT_XFER_REQUEST			= 57
Const $AW_EVENT_XFER_CANCEL				= 58
Const $AW_EVENT_LASER_BEAM				= 59
Const $AW_EVENT_XFER_QUERY				= 60
Const $AW_EVENT_CAV_TEMPLATE_CHANGE		= 61
Const $AW_MAX_EVENT						= 62


;AW Callback Constants
Const $AW_CALLBACK_CREATE						 = 0
Const $AW_CALLBACK_LOGIN						 = 1
Const $AW_CALLBACK_ENTER						 = 2
Const $AW_CALLBACK_OBJECT_RESULT				 = 3
Const $AW_CALLBACK_LICENSE_ATTRIBUTES			 = 4
Const $AW_CALLBACK_LICENSE_RESULT				 = 5
Const $AW_CALLBACK_CITIZEN_ATTRIBUTES			 = 6
Const $AW_CALLBACK_CITIZEN_RESULT				 = 7
Const $AW_CALLBACK_QUERY						 = 8
Const $AW_CALLBACK_WORLD_LIST					 = 9
Const $AW_CALLBACK_SEND_FILE					 = 10
Const $AW_CALLBACK_JOIN							 = 11
Const $AW_CALLBACK_PASSWORD_SEND				 = 12
Const $AW_CALLBACK_IMMIGRATE					 = 13
Const $AW_CALLBACK_REGISTER						 = 14
Const $AW_CALLBACK_UNIVERSE_EJECTION			 = 15
Const $AW_CALLBACK_UNIVERSE_EJECTION_RESULT		 = 16
Const $AW_CALLBACK_ADDRESS						 = 17
Const $AW_CALLBACK_WORLD_EJECTION				 = 18
Const $AW_CALLBACK_WORLD_EJECTION_RESULT		 = 19
Const $AW_CALLBACK_ADMIN_WORLD_LIST				 = 20
Const $AW_CALLBACK_ADMIN_WORLD_RESULT			 = 21
Const $AW_CALLBACK_DELETE_ALL_OBJECTS_RESULT	 = 22
Const $AW_CALLBACK_CELL_RESULT					 = 23
Const $AW_CALLBACK_RELOAD_REGISTRY				 = 24
Const $AW_CALLBACK_ATTRIBUTES_RESET_RESULT		 = 25
Const $AW_CALLBACK_ADMIN						 = 26
Const $AW_CALLBACK_CONTACT_ADD					 = 27
Const $AW_CALLBACK_TELEGRAM_RESULT				 = 28
Const $AW_CALLBACK_TERRAIN_SET_RESULT			 = 29
Const $AW_CALLBACK_TERRAIN_NEXT_RESULT			 = 30
Const $AW_CALLBACK_TERRAIN_DELETE_ALL_RESULT	 = 31
Const $AW_CALLBACK_TERRAIN_LOAD_NODE_RESULT		 = 32
Const $AW_CALLBACK_BOTGRAM_RESULT				 = 33
Const $AW_CALLBACK_USER_LIST					 = 34
Const $AW_CALLBACK_BOTMENU_RESULT				 = 35
Const $AW_CALLBACK_CAV							 = 36
Const $AW_CALLBACK_CAV_RESULT					 = 37
Const $AW_CALLBACK_WORLD_INSTANCE				 = 38
Const $AW_CALLBACK_HUD_RESULT					 = 39
Const $AW_CALLBACK_AVATAR_LOCATION				 = 40
Const $AW_CALLBACK_OBJECT_QUERY					 = 41
Const $AW_CALLBACK_WORLD_CAV_RESULT				 = 42
Const $AW_CALLBACK_WORLD_CAV					 = 43
Const $AW_CALLBACK_XFER_LOGIN					 = 44
Const $AW_CALLBACK_XFER_REQUEST_SHOW_REPLY		 = 45
Const $AW_CALLBACK_CAV_TEMPLATE_RESULT			 = 46
Const $AW_CALLBACK_SHOPITEM_ATTRIBUTES			 = 47
Const $AW_CALLBACK_SHOPITEM_RESULT				 = 48
Const $AW_CALLBACK_SHOPITEM_QUERY				 = 49
Const $AW_CALLBACK_SHOPTRANS_TOTAL				 = 50
Const $AW_CALLBACK_SHOPTRANS_RESULT				 = 51
Const $AW_CALLBACK_SHOPTRANS_BUY_RESULT			 = 52
Const $AW_CALLBACK_SHOPTRANS_LIST				 = 53
Const $AW_MAX_CALLBACK							 = 54

; AW Chat Types Constants
Const $AW_CHAT_SAID = 0
Const $AW_CHAT_BROADCAST = 1
Const $AW_CHAT_WHISPER = 2
Const $AW_CHAT_DISCONNECT = -1

; AW Channel Constants
Const $AW_CHAT_CHANNEL_NONE         = 0x00000000 ; backward compatibility, defaults to LOCAL
Const $AW_CHAT_CHANNEL_LOCAL        = 0x00000001 ; LOCAL neighborhood
Const $AW_CHAT_CHANNEL_GLOBAL       = 0x00000002 ; GLOBAL / worldwide
Const $AW_CHAT_CHANNEL_WORLD1       = 0x00000010 ; WORLD defined #1
Const $AW_CHAT_CHANNEL_WORLD2       = 0x00000020 ; WORLD defined #2
Const $AW_CHAT_CHANNEL_WORLD3       = 0x00000040 ; WORLD defined #3
Const $AW_CHAT_CHANNEL_WORLD4       = 0x00000080 ; WORLD defined #4
Const $AW_CHAT_CHANNEL_WORLD5       = 0x00000100 ; WORLD defined #5
Const $AW_CHAT_CHANNEL_UNIVERSE     = 0x01000000 ; UNIVERSAL

; AW Contact States Constants
Const $AW_CONTACT_OFFLINE = 0
Const $AW_CONTACT_ONLINE = 1
Const $AW_CONTACT_NOT_A_CITIZEN = 2
Const $AW_CONTACT_AFK = 3
Const $AW_CONTACT_UNKNOWN = 4
Const $AW_CONTACT_DELETE = 5

; AW World States Constants
Const $AW_WORLDSTATUS_UNKNOWN = 0
Const $AW_WORLDSTATUS_PUBLIC = 1
Const $AW_WORLDSTATUS_PRIVATE = 2
Const $AW_WORLDSTATUS_STOPPED = 3

; AW Server States Constants
Const $AW_SERVER_STOPPED = 0
Const $AW_SERVER_STARTING = 1
Const $AW_SERVER_START_WAIT = 2
Const $AW_SERVER_RUNNING = 3

; AW Connection Types Constants
Const $AW_CONNECTION_DIRECT = 0
Const $AW_CONNECTION_FIREWALL_NO_PROXY = 1
Const $AW_CONNECTION_PROXY_AUTO = 2
Const $AW_CONNECTION_PROXY_NO_AUTH = 3
Const $AW_CONNECTION_PROXY_BASIC = 4
Const $AW_CONNECTION_PROXY_AUTH_NTLM = 5
Const $AW_CONNECTION_MAX = 6

; AW Connection States Constants
Const $AW_CONNECTION_STATE_NOT_CONNECTED = 0
Const $AW_CONNECTION_STATE_CONNECTING_TO_PROXY = 1
Const $AW_CONNECTION_STATE_NEGOTIATING_WITH_PROXY = 2
Const $AW_CONNECTION_STATE_CONNECTING_TO_TUNNEL = 3
Const $AW_CONNECTION_STATE_CONNECTING_TO_UNIVERSE = 4
Const $AW_CONNECTION_STATE_CONNECTED = 5
Const $AW_CONNECTION_STATE_PASSWORD_REQUIRED = 6

; AW Ejection Types
Const $AW_EJECT_BY_ADDRESS = 0
Const $AW_EJECT_BY_COMPUTER = 1
Const $AW_EJECT_BY_CITIZEN = 2

; AW Avatar States Constants
Const $AW_AVATAR_STATE_WALKING = 0
Const $AW_AVATAR_STATE_RUNNING = 2
Const $AW_AVATAR_STATE_FLYING = 3
Const $AW_AVATAR_STATE_SWIMMING = 4
Const $AW_AVATAR_STATE_FALLING = 5
Const $AW_AVATAR_STATE_JUMPING = 6
Const $AW_AVATAR_STATE_WARPING = 7
Const $AW_AVATAR_STATE_RIDING = 8
Const $AW_AVATAR_STATE_SLIDING1 = 9
Const $AW_AVATAR_STATE_SLIDING2 = 10
Const $AW_AVATAR_STATE_SLIDING3 = 11
Const $AW_AVATAR_STATE_CLIMBING = 12

; AW Zone Types Constants
Const $AW_ZONE_TYPE_CUBE = 0
Const $AW_ZONE_TYPE_CYLINDER = 1
Const $AW_ZONE_TYPE_SPHERE = 2

; AW Particle Types Constants
Const $AW_PARTICLE_TYPE_SPRITE = 0
Const $AW_PARTICLE_TYPE_FACER = 1
Const $AW_PARTICLE_TYPE_FLAT = 2
Const $AW_PARTICLE_TYPE_OBJECT = 3

; AW Particle Draw Styles Constants
Const $AW_PARTICLE_DRAW_NORMAL = 0
Const $AW_PARTICLE_DRAW_BRIGHT = 1
Const $AW_PARTICLE_DRAW_GLOW = 2

; AW Camera Types Constants
Const $AW_CAMERA_TRACK_DEFAULT = 0
Const $AW_CAMERA_TRACK_AVATAR = 1
Const $AW_CAMERA_TRACK_OBJECT = 2
Const $AW_CAMERA_TRACK_AHEAD = 3
Const $AW_CAMERA_TRACK_SELF_FIRST_PERSON = 4
Const $AW_CAMERA_TRACK_SELF_LOCKED = 5
Const $AW_CAMERA_TRACK_SELF_CHASE = 6
Const $AW_CAMERA_TRACK_SELF_FRONT = 7

; AW Register Methods Constants
Const $AW_REGISTER_MONTHLY = 0
Const $AW_REGISTER_ANNUAL = 1
Const $AW_REGISTER_USER = 2

; AW Avatar Set Flags Constants
Const $AW_AVATAR_SET_NONE      = 0x00
Const $AW_AVATAR_SET_POSITION  = 0x01
Const $AW_AVATAR_SET_TYPE      = 0x02
Const $AW_AVATAR_SET_GESTURE   = 0x04
Const $AW_AVATAR_SET_STATE     = 0x08

; AW Entity Types Constants
Const $AW_ENTITY_AVATAR = 0 ; not used as such
Const $AW_ENTITY_MOVER  = 1

; AW Mover State Types Constants
Const $AW_MOVER_STATE_IDLE = 0   ; never set by SDK
Const $AW_MOVER_STATE_START = 1
Const $AW_MOVER_STATE_MOVE = 2    ; never set by SDK
Const $AW_MOVER_STATE_PAUSE = 3
Const $AW_MOVER_STATE_CONTINUE = 4
Const $AW_MOVER_STATE_STOP = 5
Const $AW_MOVER_STATE_RESET = 6

; AW Mover Flags Constants
Const $AW_MOVER_FLAG_LOOP                  = 0x00000001
Const $AW_MOVER_FLAG_USE_OBJTAG            = 0x00000002
Const $AW_MOVER_FLAG_BUMP_ADD              = 0x00000004
Const $AW_MOVER_FLAG_CLICK_START           = 0x00000008
Const $AW_MOVER_FLAG_CLICK_PAUSE           = 0x00000010
Const $AW_MOVER_FLAG_LOCK_POSITION         = 0x00000020
Const $AW_MOVER_FLAG_LOCK_YAW              = 0x00000040
Const $AW_MOVER_FLAG_LOCK_PITCH            = 0x00000080
Const $AW_MOVER_FLAG_SINGLE_RIDER          = 0x00000100
Const $AW_MOVER_FLAG_NO_AUTO_YAW           = 0x00000200
Const $AW_MOVER_FLAG_EMPTY_RESET           = 0x00000400
Const $AW_MOVER_FLAG_DISABLE_FLYING        = 0x00000800
Const $AW_MOVER_FLAG_KEEP_ON_WATER         = 0x00001000
Const $AW_MOVER_FLAG_DISABLE_UPWARDS       = 0x00002000
Const $AW_MOVER_FLAG_INVISIBLE_AV          = 0x00004000
Const $AW_MOVER_FLAG_EXIT_EJECT_UP         = 0x00008000
Const $AW_MOVER_FLAG_EXIT_NON_SOLID        = 0x00010000
Const $AW_MOVER_FLAG_AV_APPLY_TILT_X       = 0x00020000
Const $AW_MOVER_FLAG_AV_APPLY_TILT_Z       = 0x00040000
Const $AW_MOVER_FLAG_OBJECT_LINK           = 0x00080000
Const $AW_MOVER_FLAG_DISABLE_MOVE          = 0x00100000
Const $AW_MOVER_FLAG_TILT_BY_TERRAIN       = 0x00200000
Const $AW_MOVER_FLAG_DISABLE_EXPL_SEQS     = 0x00400000
Const $AW_MOVER_FLAG_DISABLE_TURN_ON_PLACE = 0x00800000
Const $AW_MOVER_FLAG_DISABLE_TELEPORTS     = 0x01000000
Const $AW_MOVER_FLAG_DETACH_ON_TELEPORT    = 0x02000000

; AW Mover Types Constants
Const $AW_MOVER_TYPE_PASSIVE = 0
Const $AW_MOVER_TYPE_ACTIVE = 1
Const $AW_MOVER_TYPE_ITEM = 2

; AW Zones Flags
Const $AW_ZONE_FLAG_WATER              = 0x01
Const $AW_ZONE_FLAG_BLOCK_PARTICLES    = 0x02
Const $AW_ZONE_FLAG_BLOCK_LIGHTS       = 0x04
Const $AW_ZONE_FLAG_BLOCK_WORLD_LIGHT  = 0x08
Const $AW_ZONE_FLAG_BLOCK_CHAT         = 0x10
Const $AW_ZONE_FLAG_VISIBLE            = 0x20
Const $AW_ZONE_FLAG_BLOCK_JOIN         = 0x40
Const $AW_ZONE_FLAG_VOIP               = 0x80
Const $AW_ZONE_FLAG_BLOCK_AUDIO        = 0x100

; AW Particles Flags
Const $AW_PARTICLE_FLAG_INTERPOLATE    = 0x01
Const $AW_PARTICLE_FLAG_GRAVITY        = 0x02
Const $AW_PARTICLE_FLAG_COLLIDE_ZONES  = 0x04
Const $AW_PARTICLE_FLAG_ZONE_EXCLUSIVE = 0x08
Const $AW_PARTICLE_FLAG_CAMERA_EMIT    = 0x10
Const $AW_PARTICLE_FLAG_MOVER_LINK     = 0x20
Const $AW_PARTICLE_FLAG_DRAW_IN_FRONT  = 0x40
Const $AW_PARTICLE_FLAG_APPLY_ROTATION = 0x80

; AW Camera Flags
Const $AW_CAMERA_FLAG_TRACK_USER       = 0x01

; AW Cloth Types
Const $AW_CLOTH_TYPE_FABRIC = 0
Const $AW_CLOTH_TYPE_OBJECT = 1
Const $AW_CLOTH_TYPE_METAL_SHAPE = 2

; AW Cloth Flags
Const $AW_CLOTH_FLAG_GRAVITY             = 0x0001
Const $AW_CLOTH_FLAG_STATIC              = 0x0002
Const $AW_CLOTH_FLAG_COMDAMPING          = 0x0004
Const $AW_CLOTH_FLAG_BENDING_ORTHO       = 0x0008
Const $AW_CLOTH_FLAG_SELFCOLLISION       = 0x0010
Const $AW_CLOTH_FLAG_COLLISION_TWO_WAY   = 0x0020
Const $AW_CLOTH_FLAG_ATTACHMENT_TWO_WAY  = 0x0040
Const $AW_CLOTH_FLAG_ATTACHMENT_TEARABLE = 0x0080
Const $AW_CLOTH_FLAG_TEARABLE            = 0x0100
Const $AW_CLOTH_FLAG_TEARABLE_DIAGONAL   = 0x0200 ; fabric only
Const $AW_CLOTH_FLAG_PRESSURE            = 0x0400 ; closed convex hulls only
Const $AW_CLOTH_FLAG_ADHERE              = 0x0800
Const $AW_CLOTH_FLAG_UNTANGLING          = 0x1000
Const $AW_CLOTH_FLAG_HARD_STRETCH_LIMIT  = 0x2000
Const $AW_CLOTH_FLAG_TEX_NO_MIRROR       = 0x4000

; AW Cloth Anchors
Const $AW_CLOTH_ANCHOR_NONE = 0
Const $AW_CLOTH_ANCHOR_GLOBAL = 1
Const $AW_CLOTH_ANCHOR_OBJECT = 2

; AW Cloth Anchor Pos
Const $AW_CLOTH_ANCHOR_POS_CENTER = 0
Const $AW_CLOTH_ANCHOR_POS_TOP = 1
Const $AW_CLOTH_ANCHOR_POS_BOTTOM = 2
Const $AW_CLOTH_ANCHOR_POS_LEFT = 3
Const $AW_CLOTH_ANCHOR_POS_RIGHT = 4
Const $AW_CLOTH_ANCHOR_POS_TOP_LEFT = 5
Const $AW_CLOTH_ANCHOR_POS_TOP_RIGHT = 6
Const $AW_CLOTH_ANCHOR_POS_BOTTOM_LEFT = 7
Const $AW_CLOTH_ANCHOR_POS_BOTTOM_RIGHT = 8

; AW Cloth Fabric Shapes
Const $AW_CLOTH_FABRIC_SHAPE_QUAD = 0
Const $AW_CLOTH_FABRIC_SHAPE_DISC = 1

; AW Cloth Metal Shapes
Const $AW_CLOTH_METAL_SHAPE_BOX = 0
Const $AW_CLOTH_METAL_SHAPE_SPHERE = 1
Const $AW_CLOTH_METAL_SHAPE_CAPSULE = 2

; AW Object Types Constants
Const $AW_OBJECT_TYPE_V3       = 0
Const $AW_OBJECT_TYPE_UNKNOW = 1
Const $AW_OBJECT_TYPE_ZONE = 2
Const $AW_OBJECT_TYPE_PARTICLES = 3
Const $AW_OBJECT_TYPE_MOVER = 4
Const $AW_OBJECT_TYPE_CAMERA = 5
COnst $AW_OBJECT_TYPE_CLOTH = 6
Const $AW_MAX_OBJECT_TYPES = 7

; AW HUD Origin Types Constants
Const $AW_HUD_ORIGIN_TOP_LEFT  = 0
Const $AW_HUD_ORIGIN_TOP = 1
Const $AW_HUD_ORIGIN_TOP_RIGHT = 2
Const $AW_HUD_ORIGIN_LEFT = 3
Const $AW_HUD_ORIGIN_CENTER = 4
Const $AW_HUD_ORIGIN_RIGHT = 5
Const $AW_HUD_ORIGIN_BOTTOM_LEFT = 6
Const $AW_HUD_ORIGIN_BOTTOM = 7
Const $AW_HUD_ORIGIN_BOTTOM_RIGHT = 8

; AW HUD Types Constants
Const $AW_HUD_TYPE_TEXT  = 0
Const $AW_HUD_TYPE_IMAGE = 1
Const $AW_HUD_TYPE_MODEL = 2

; AW HUD Element Flags Enum
Const $AW_HUD_ELEMENT_FLAG_CLICKS        = 0x0001
Const $AW_HUD_ELEMENT_FLAG_STRETCH       = 0x0002
Const $AW_HUD_ELEMENT_FLAG_ADDITIVE      = 0x0004
Const $AW_HUD_ELEMENT_FLAG_SIZE_PERCENT  = 0x0008
Const $AW_HUD_ELEMENT_FLAG_TRANSITION    = 0x0010
Const $AW_HUD_ELEMENT_FLAG_TEMPORARY     = 0x0020
Const $AW_HUD_ELEMENT_FLAG_UNIVERSE_PATH = 0x0040
Const $AW_HUD_ELEMENT_FLAG_CLAMP         = 0x0080
Const $AW_HUD_ELEMENT_FLAG_HIGHLIGHT     = 0x0100

; AW Privacy Types
Const $AW_PRIVACY_BLOCK_TELEGRAMS  = 0x0001

; AW Enable CAV Types Constants
Const $AW_ENABLE_CAV_CITIZEN       = 0x01
Const $AW_ENABLE_CAV_BOT           = 0x02
Const $AW_ENABLE_CAV_TOURIST       = 0x04
Const $AW_ENABLE_CAV_WORLD_CITIZEN = 0x10
Const $AW_ENABLE_CAV_WORLD_BOT     = 0x20
Const $AW_ENABLE_CAV_WORLD_TOURIST = 0x40

; AW Xfer Types
Const $AW_XFER_TYPE_FILE     = 0
Const $AW_XFER_TYPE_IMAGE    = 1
Const $AW_XFER_TYPE_DOCUMENT = 2
Const $AW_XFER_TYPE_MEDIA    = 3
Const $AW_XFER_TYPE_STORE    = 4	; file to store
Const $AW_XFER_TYPE_RETRIEVE = 5	; file to retrieve

; AW Lasewr Beam Source Type
Const $AW_LASER_BEAM_SOURCE_TYPE_NONE    = 0
Const $AW_LASER_BEAM_SOURCE_TYPE_AVATAR  = 1
Const $AW_LASER_BEAM_SOURCE_TYPE_OBJECT  = 2
Const $AW_LASER_BEAM_SOURCE_TYPE_COORDS  = 3

; AW Laser Beam Target Type
Const $AW_LASER_BEAM_TARGET_TYPE_NONE    = 0
Const $AW_LASER_BEAM_TARGET_TYPE_AVATAR  = 1
Const $AW_LASER_BEAM_TARGET_TYPE_OBJECT  = 2
Const $AW_LASER_BEAM_TARGET_TYPE_COORDS  = 3

; AW Laser Beam Style
Const $AW_LASER_BEAM_STYLE_LINE          = 0
Const $AW_LASER_BEAM_STYLE_PARTICLE      = 1

; AW Shop Item Type
Const $AW_SHOPITEM_TYPE_CAV              = 0
